#!/usr/bin/env bash
# Displays a list of currently running processes.
#+   Shows all processes, for all users, including those
#+  which might not have a TTY.

#It shows all the processes running on the system.
ps -auxf