#!/usr/bin/env bash
# Manages the script manage_my_process.
#   When passed the argument `start`:
#     1. Starts manage_my_process
#     2. Creates a file containings its PID in /var/run/my_process.pid
#     3. Displays "manage_my_process started"
#   When passed the argument `stop`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Displays "manage_my_process stopped"
#   When passed the argument `restart`:
#     1. Stops manage_my_process
#     2. Deletes the file /var/run/my_process.pid
#     3. Starts manage_my_process
#     4. Creates a file containing its PID in /var/run/my_process.pid
#     5. Displays "manage_my_process restarted"
#   If any other or no arguments are passed, displays
#+  "Usage: manage_my_process {start|stop|restart}"

# manages manage_my_process by either starting it, stopping it or restarting it.

command="$1"

if [ -z "$command" ]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit
fi

if [ "$command" == "start" ]; then

  bash ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$command" == "stop" ]; then
  [ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid
  echo "manage_my_process stopped"

elif [ "$command" == "restart" ]; then

  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}"
fi