#!/usr/bin/env bash
# Display "To infinity and Beyond" indefinitely with
# a sleep 2 in between each iteration.
# Displays "I am incincible!!!" in between each iteration.

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
