#!/usr/bin/env bash
# This script is used for FizzBuzz game
#1. The first line of the script is a comment that explains what the script does.
#2. The second line sets the variable n to 1.
#3. The third line of the script is a while loop that will execute as long as the value of n is less than or equal to 100.
#4. The fourth line of the script is an if statement that checks if n is divisible by 3 and 5.
#5. The fifth line of the script is an if statement that checks if n is divisible by 3.
#6. The sixth line of the script is an if statement that checks if n is divisible by 5.
#7. The seventh line of the script is an if statement that checks if n is not divisible by 3 or 5.
#8. The eighth line of the script is an echo statement that prints the value of n.
#9. The ninth line of the script increments the value of n by 1.
#10. The tenth line of the script is a done statement that ends the while loop.
n=1

while [ $n -le 100 ]
do
    if [ $(( n % 3 )) -eq 0 -a $(( n % 5 )) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $(( n % 3 )) -eq 0 ]
    then
        echo "Fizz"
    elif [ $(( n % 5 )) -eq 0 ]
    then
        echo "Buzz"
    else
        echo $n
    fi
    n=$(( n + 1 ))
done
