#!/usr/bin/env bash
# displays information about the School file

#!/usr/bin/env bash
# Displays information about the file `school`.

#1. The first if statement checks to see if the file “school” exists.
#2. If it does, it checks to see if the file is empty.
#3. If it is not empty, it prints a message saying that the file is not empty.
#4. If it is empty, it prints a message saying that the file is empty.
#5. If the file does not exist, it prints a message saying that the file does not exist.
if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
